image: gitlab.sigasi.com:4567/dev/sigasi_insights:latest

stages:
  - prebuild
  - deploy

pre-branch-build:
  stage: prebuild
  tags:
    - hugo
  except:
    refs:
      - master
  script:
    - node ./prebuild.mjs
  # the above script generates a build.env env file
  # the below artifact converts this build.env file to usable environment variables in CI
  artifacts:
    reports:
      dotenv: build.env

deploy-prod:
  stage: deploy
  tags:
    - hugo
  script: 
    - git submodule update --init --recursive
    - hugo --minify
    - firebase deploy -m "$CI_COMMIT_TITLE" --token $FIREBASE_TOKEN
    - 'curl -X POST "https://ohdear.app/api/checks/45757/request-run" \
        -H "Authorization: Bearer $OHDEAR_TOKEN" \
        -H "Accept: application/json" \
        -H "Content-Type: application/json"'
  only:
    refs:
      - master
  environment:
    name: production
    url: https://insights.sigasi.com

deploy-branch:
  stage: deploy
  tags:
    - hugo
  script: 
    - git submodule update --init --recursive
    - hugo --buildFuture --baseURL $MY_DEPLOYED_URL
    - echo $CI_COMMIT_TITLE
    - firebase hosting:channel:deploy $CI_COMMIT_REF_SLUG --token $FIREBASE_TOKEN
  except:
    refs:
      - master
  needs:
    - job: pre-branch-build
      artifacts: true
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $MY_DEPLOYED_URL

# stop_branch:
#   stage: deploy
#   tags:
#     - hugo
#   rules:
#     - if: '$CI_COMMIT_BRANCH != "master"'
#       when: manual
#     - when: never
#   script:
#     - firebase hosting:channel:delete -f $CI_COMMIT_REF_SLUG
#   environment:
#     name: review/$CI_COMMIT_REF_NAME
#     action: stop
