baseurl         = "https://insights.sigasi.com/"
title           = "Sigasi"

contentdir      = "content"
layoutdir       = "layouts"
publishdir      = "public"
assetdir        = "assets"

paginate        = 15
canonifyurls    = true
summarylength   = 20
googleAnalytics = "UA-2852630-4"
disqusShortname = "sigasi"

enableRobotsTXT = "true"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsCodeFences = "true"
pygmentsUseClasses = "true"

[author]
    name = "Sigasi"

[taxonomies]
  tag = "tags"

[markup]
  [markup.tableOfContents]
    endlevel = 2
    ordered = false
    startLevel = 1

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
