baseurl         = "https://insights.sigasi.com/"
title           = "Sigasi"

theme           = "sigasi_theme"
contentdir      = "content"
layoutdir       = "layouts"
assetdir        = "assets"
publishdir      = "public"

paginate        = 15
canonifyurls    = true
summarylength   = 20
googleAnalytics = "UA-2852630-4"
disqusShortname = "sigasi"

enableRobotsTXT = "true"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsCodeFences = "true"
pygmentsUseClasses = "true"

[author]
    name = "Sigasi"

[params]
  description         = "Design. Verify. Keep Moving. Edit your VHDL, Verilog, and SystemVerilog code using the Sigasi Studio IDE"

  MatomoURL = "analytics.sigasi.com"
  MatomoID  = "2"

  images = ['/img/logo_positive_900x900']

[social]
  twitter = 'Sigasi'

[taxonomies]
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'date'
    weight = 10

[markup]
  [markup.tableOfContents]
    endlevel = 2
    ordered = false
    startLevel = 1

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "products"
    name = "Our Solutions"
    url = "https://www.sigasi.com/products/"
    weight = 10
  [[menu.main]]
    identifier = "trybuy"
    name = "Try & Buy"
    url = "https://www.sigasi.com/try-buy/"
    weight = 20
  [[menu.main]]
    identifier = "insights"
    name = "Insights"
    url = "/"
    weight = 30
  [[menu.main]]
      parent = "products"
    identifier = "SiStE"
    name = "Sigasi Studio Eclipse"
    url = "https://www.sigasi.com/products/"
    weight = 10
  [[menu.main]]
    parent = "products"
    identifier = "SiStVSC"
    name = "VS Code Extension"
    url = "https://www.sigasi.com/vscode/"
    weight = 20
  [[menu.main]]
    parent = "products"
    identifier = "Veresta"
    name = "Veresta"
    url = "https://www.sigasi.com/veresta/"
    weight = 30
  [[menu.main]]
    parent = "products"
    identifier = "sdk"
    name = "Sigasi SDK"
    url = "https://www.sigasi.com/sdk/"
    weight = 40

  [[menu.main]]
    parent = "trybuy"
    identifier = "online"
    name = "Try Sigasi Online"
    url = "https://www.sigasi.com/online/"
    weight = 5
  [[menu.main]]
    parent = "trybuy"
    identifier = "download"
    name = "Download"
    url = "https://www.sigasi.com/download/"
    weight = 10
  [[menu.main]]
    parent = "trybuy"
    identifier = "license"
    name = "Get Your License"
    url = "https://www.sigasi.com/try-form/"
    weight = 20
  [[menu.main]]
    parent = "trybuy"
    identifier = "buy"
    name = "Buy"
    url = "https://www.sigasi.com/buy/"
    weight = 30

  [[menu.main]]
    parent = "insights"
    name = "Manual"
    url = "/manual/"
    weight = 10
  [[menu.main]]
    parent = "insights"
    name = "FAQ"
    url = "/faq/"
    weight = 20
  [[menu.main]]
    parent = "insights"
    name = "Release Notes"
    url = "/releasenotes/"
    weight = 30
  [[menu.main]]
    parent = "insights"
    name = "Screencasts"
    url = "/screencasts/"
    weight = 40
  [[menu.main]]
    parent = "insights"
    name = "Tech Articles"
    url = "/tech/"
    weight = 50
  [[menu.main]]
    parent = "insights"
    name = "VS Code"
    url = "/vscode/"
    weight = 60

  [[menu.mobile]]
    url = "https://www.sigasi.com/"
    name = "Sigasi"
    weight = 1
  [[menu.mobile]]
    url = "/"
    name = "Insights"
    weight = 2
  [[menu.mobile]]
    url = "/manual/"
    name = "Manual"
    weight = 3
  [[menu.mobile]]
    url = "/faq/"
    name = "FAQ"
    weight = 4
  [[menu.mobile]]
    url = "/releasenotes/"
    name = "Release Notes"
    weight = 5
  [[menu.mobile]]
    url = "/screencasts/"
    name = "Screencasts"
    weight = 6
  [[menu.mobile]]
    url = "/tech/"
    name = "Tech Articles"
    weight = 7
  [[menu.mobile]]
    url = "/vscode/"
    name = "VS Code"
    weight = 8
  [[menu.mobile]]
    url = "/veresta/"
    name = "Veresta"
    weight = 9

  [[menu.footer]]
    name = "Mission Statement"
    url = "https://www.sigasi.com/mission-statement/"
    weight = 10
  [[menu.footer]]
    name = "News"
    url = "https://www.sigasi.com/news/"
    weight = 15
  [[menu.footer]]
    name = "Jobs"
    url = "https://www.sigasi.com/jobs/"
    weight = 20
  [[menu.footer]]
    name = "Who's Who"
    url = "https://www.sigasi.com/about/"
    weight = 30
  [[menu.footer]]
    name = "Contact"
    url = "https://www.sigasi.com/contact/"
    weight = 40
  [[menu.footer]]
    name = "Support"
    url = "https://www.sigasi.com/support/"
    weight = 90
