[context.production.environment]
  HUGO_VERSION = "0.55.6"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.6"

[context.deploy-preview]
  command = "hugo version; hugo -b $DEPLOY_PRIME_URL"
  publish = "public/"

