[build.environment]
  HUGO_VERSION = "0.74.3"

[build]
  publish = "public/"

[context.production]
  command = "hugo version; hugo --minify"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=600, must-revalidate"
    referrer-policy = "strict-origin-when-cross-origin"
    x-frame-options = "DENY"
    Content-Security-Policy-reportOnly = "default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://sigasi.report-uri.com/r/d/csp/wizard"

[context.deploy-preview]
  command = "hugo version; hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

