[build.environment]
  HUGO_VERSION = "0.74.3"

[build]
  publish = "public/"

[context.production]
  command = "git submodule update --init --recursive; hugo version; hugo --minify"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=600, must-revalidate"
    referrer-policy = "strict-origin-when-cross-origin"
    x-frame-options = "DENY"

[context.deploy-preview]
  command = "git submodule update --init --recursive; hugo version; hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

