[build.environment]
  HUGO_VERSION = "0.67.1"

[build]
  publish = "public/"

[context.production]
  command = "hugo version; hugo --minify"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=600, must-revalidate"

[context.deploy-preview]
  command = "hugo version; hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
